### ISSUE TITLE
Upgrade old procedures files

### ISSUE THREAD

**Issue by dyf** [AllenNeuralDynamics/aind-metadata-upgrader#4]
# User story
As a user, I want to upgrade and validate old version of `procedures.json` files, particularly in files that predate the addition of the `Surgery` model, so that our data can be consistent and more easily searchable.

# Acceptance criteria
- [ ] a new procedures upgrader class exists
- [ ] the upgrader works on procedures.json that don't have a surgery model
- [ ] the upgrader uses `schema_version` to decide how to upgrade things (e.g. if schema_version < 0.12.0 then ...).

# Sprint Ready Checklist 
- [ ] 1. Acceptance criteria defined 
- [ ] 2. Team understands acceptance criteria 
- [ ] 3. Team has defined solution / steps to satisfy acceptance criteria 
- [ ] 4. Acceptance criteria is verifiable / testable 
- [ ] 5. External / 3rd Party dependencies identified
- [ ] 6. Ticket is prioritized and sized

# Notes
*Add any helpful notes here.*

**Comment by Sun-flow** [comment]
Need example procedures files from different projects @saskiad
