### ISSUE TITLE
modality-related KeyErrors when upgrading DDs

### ISSUE THREAD

**Issue by Sun-flow** [AllenNeuralDynamics/aind-metadata-upgrader#47]
When upgrading DDs in another PR, encountering many failed upgrades due to unmapped `Modality`s. 

Includes: `[HSFP, FIP, trained-behaviors, diSPIM, multiplane-ophys]`

Some of these might be taken care of when duplicate records are removed in https://github.com/AllenNeuralDynamics/aind-data-migration-scripts/issues/153

**Comment by dyf** [comment]
`HSFP` -> `fib`
`FIP` -> `fib`
`trained-behaviors` -> `behavior`
`diSPIM` -> `SPIM`
`multiplane-ophys` -> `pophys`
