### ISSUE TITLE
DataDescription.data_level needs a validator for valid tags

### ISSUE THREAD

**Issue by Sun-flow** [AllenNeuralDynamics/aind-metadata-upgrader#9]
**Is your feature request related to a problem? Please describe.**
Users are currently still uploading data which includes outdated `data_level` tags, which need to be then updated manually (via a script that is already written) to our current tag standards.

**Describe the solution you'd like**
Introduce a validator to `DataDescription` that checks whether the tag input is valid or not, and converts it to a valid analog if not. If there is no valid analog, reject the model.

**Describe alternatives you've considered**
We could also solve this via running the `data_description_upgrade` over all `DataDescription`s regularly, but this requires a lot of oversight.

**Comment by jtyoung84** [comment]
Closing this. The validation is done through the enum definitions. This is most likely an issue with getting people to use the latest version of aind-data-schema and getting people to not bypass the validation checks.
